apps/apiclient/urls.py
from django.conf.urls import url
from apiclient import views


urlpatterns = [
    url(r'^oauth/$', views.oauth, name='apiclient_oauth'),
    url(r'^oauth_callback/$', views.oauth_callback, name='apiclient_oauth_callback'),
]

apps/cover/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of FNP-Redakcja, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from django.conf.urls import url
from cover import views


urlpatterns = [
    url(r'^preview/$', views.preview_from_xml, name='cover_preview'),
    url(r'^preview/(?P<book>[^/]+)/$', views.preview, name='cover_preview'),
    url(r'^preview/(?P<book>[^/]+)/(?P<chunk>[^/]+)/$',
            views.preview, name='cover_preview'),
    url(r'^preview/(?P<book>[^/]+)/(?P<chunk>[^/]+)/(?P<rev>\d+)/$',
            views.preview, name='cover_preview'),

    url(r'^image/$', views.image_list, name='cover_image_list'),
    url(r'^image/(?P<pk>\d+)/?$', views.image, name='cover_image'),
    url(r'^image/(?P<pk>\d+)/file/', views.image_file, name='cover_file'),
    url(r'^add_image/$', views.add_image, name='cover_add_image'),
]

apps/wiki/urls.py
# -*- coding: utf-8
from django.conf.urls import url
from wiki import views


urlpatterns = [
    url(r'^edit/(?P<slug>[^/]+)/(?:(?P<chunk>[^/]+)/)?$',
        views.editor, name="wiki_editor"),

    url(r'^readonly/(?P<slug>[^/]+)/(?:(?P<chunk>[^/]+)/)?$',
        views.editor_readonly, name="wiki_editor_readonly"),

    url(r'^gallery/(?P<directory>[^/]+)/$',
        views.gallery, name="wiki_gallery"),

    url(r'^history/(?P<chunk_id>\d+)/$',
        views.history, name="wiki_history"),

    url(r'^rev/(?P<chunk_id>\d+)/$',
        views.revision, name="wiki_revision"),

    url(r'^text/(?P<chunk_id>\d+)/$',
        views.text, name="wiki_text"),

    url(r'^revert/(?P<chunk_id>\d+)/$',
        views.revert, name='wiki_revert'),

    url(r'^diff/(?P<chunk_id>\d+)/$', views.diff, name="wiki_diff"),
    url(r'^pubmark/(?P<chunk_id>\d+)/$', views.pubmark, name="wiki_pubmark"),

    url(r'^themes$', views.themes, name="themes"),
]

redakcja/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView


urlpatterns = []

if getattr(settings, 'CAS_SERVER_URL', None):
    from django_cas.views import login, logout
    urlpatterns += [
        # Auth
        url(r'^accounts/login/$', login, name='login'),
        url(r'^accounts/logout/$', logout, name='logout'),
        url(r'^admin/login/$', login, name='login'),
        url(r'^admin/logout/$', logout, name='logout'),
    ]
else:
    from django.contrib.auth.views import login, logout
    urlpatterns += [
        url(r'^accounts/login/$', login, name='login'),
        url(r'^accounts/logout/$', logout, name='logout'),
    ]

urlpatterns += [
    # Admin panel
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', RedirectView.as_view(url= '/documents/', permanent=False)),
    url(r'^documents/', include('catalogue.urls')),
    url(r'^apiclient/', include('apiclient.urls')),
    url(r'^editor/', include('wiki.urls')),
    url(r'^images/', include('wiki_img.urls')),
    url(r'^cover/', include('cover.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalogue/models/book.py
# -*- coding: utf-8 -*-
#
# This file is part of FNP-Redakcja, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from django.contrib.sites.models import Site
from django.db import models, transaction
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from slugify import slugify


import apiclient
from catalogue.helpers import cached_in_field, GalleryMerger
from catalogue.models import BookPublishRecord, ChunkPublishRecord, Project
from catalogue.signals import post_publish
from catalogue.tasks import refresh_instance, book_content_updated
from catalogue.xml_tools import compile_text, split_xml
from cover.models import Image
import os
import shutil
import re

class Book(models.Model):
    """ A document edited on the wiki """

    title = models.CharField(_('title'), max_length=255, db_index=True)
    slug = models.SlugField(_('slug'), max_length=128, unique=True, db_index=True)
    public = models.BooleanField(_('public'), default=True, db_index=True)
    gallery = models.CharField(_('scan gallery name'), max_length=255, blank=True)
    project = models.ForeignKey(Project, null=True, blank=True)

    #wl_slug = models.CharField(_('title'), max_length=255, null=True, db_index=True, editable=False)
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name=_('parent'), related_name="children", editable=False)
    parent_number = models.IntegerField(_('parent number'), null=True, blank=True, db_index=True, editable=False)

    # Cache
    _short_html = models.TextField(null=True, blank=True, editable=False)
    _single = models.NullBooleanField(editable=False, db_index=True)
    _new_publishable = models.NullBooleanField(editable=False)
    _published = models.NullBooleanField(editable=False)
    _on_track = models.IntegerField(null=True, blank=True, db_index=True, editable=False)
    dc_cover_image = models.ForeignKey(Image, blank=True, null=True,
        db_index=True, on_delete=models.SET_NULL, editable=False)
    dc_slug = models.CharField(max_length=128, null=True, blank=True,
            editable=False, db_index=True)

    class NoTextError(BaseException):
        pass

    class Meta:
        app_label = 'catalogue'
        ordering = ['title', 'slug']
        verbose_name = _('book')
        verbose_name_plural = _('books')


    # Representing
    # ============

    def __iter__(self):
        return iter(self.chunk_set.all())

    def __getitem__(self, chunk):
        return self.chunk_set.all()[chunk]

    def __len__(self):
        return self.chunk_set.count()

    def __nonzero__(self):
        """
            Necessary so that __len__ isn't used for bool evaluation.
        """
        return True

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ("catalogue_book", [self.slug])

    def correct_about(self):
        return "http://%s%s" % (
            Site.objects.get_current().domain,
            self.get_absolute_url()
        )

    def gallery_path(self):
        return os.path.join(settings.MEDIA_ROOT, settings.IMAGE_DIR, self.gallery)

    def gallery_url(self):
        return '%s%s%s/' % (settings.MEDIA_URL, settings.IMAGE_DIR, self.gallery)

    # Creating & manipulating
    # =======================

    def accessible(self, request):
        return self.public or request.user.is_authenticated()

    @classmethod
    @transaction.atomic
    def create(cls, creator, text, *args, **kwargs):
        b = cls.objects.create(*args, **kwargs)
        b.chunk_set.all().update(creator=creator)
        b[0].commit(text, author=creator)
        return b

    def add(self, *args, **kwargs):
        """Add a new chunk at the end."""
        return self.chunk_set.reverse()[0].split(*args, **kwargs)

    @classmethod
    @transaction.atomic
    def import_xml_text(cls, text=u'', previous_book=None,
                commit_args=None, **kwargs):
        """Imports a book from XML, splitting it into chunks as necessary."""
        texts = split_xml(text)
        if previous_book:
            instance = previous_book
        else:
            instance = cls(**kwargs)
            instance.save()

        # if there are more parts, set the rest to empty strings
        book_len = len(instance)
        for i in range(book_len - len(texts)):
            texts.append((u'pusta część %d' % (i + 1), u''))

        i = 0
        for i, (title, text) in enumerate(texts):
            if not title:
                title = u'część %d' % (i + 1)

            slug = slugify(title)

            if i < book_len:
                chunk = instance[i]
                chunk.slug = slug[:50]
                chunk.title = title[:255]
                chunk.save()
            else:
                chunk = instance.add(slug, title)

            chunk.commit(text, **commit_args)

        return instance

    def make_chunk_slug(self, proposed):
        """ 
            Finds a chunk slug not yet used in the book.
        """
        slugs = set(c.slug for c in self)
        i = 1
        new_slug = proposed[:50]
        while new_slug in slugs:
            new_slug = "%s_%d" % (proposed[:45], i)
            i += 1
        return new_slug

    @transaction.atomic
    def append(self, other, slugs=None, titles=None):
        """Add all chunks of another book to self."""
        assert self != other

        number = self[len(self) - 1].number + 1
        len_other = len(other)
        single = len_other == 1

        if slugs is not None:
            assert len(slugs) == len_other
        if titles is not None:
            assert len(titles) == len_other
            if slugs is None:
                slugs = [slugify(t) for t in titles]

        for i, chunk in enumerate(other):
            # move chunk to new book
            chunk.book = self
            chunk.number = number

            if titles is None:
                # try some title guessing
                if other.title.startswith(self.title):
                    other_title_part = other.title[len(self.title):].lstrip(' /')
                else:
                    other_title_part = other.title

                if single:
                    # special treatment for appending one-parters:
                    # just use the guessed title and original book slug
                    chunk.title = other_title_part
                    if other.slug.startswith(self.slug):
                        chunk.slug = other.slug[len(self.slug):].lstrip('-_')
                    else:
                        chunk.slug = other.slug
                else:
                    chunk.title = ("%s, %s" % (other_title_part, chunk.title))[:255]
            else:
                chunk.slug = slugs[i]
                chunk.title = titles[i]

            chunk.slug = self.make_chunk_slug(chunk.slug)
            chunk.save()
            number += 1
        assert not other.chunk_set.exists()

        gm = GalleryMerger(self.gallery, other.gallery)
        self.gallery = gm.merge()

        # and move the gallery starts
        if gm.was_merged:
                for chunk in self[len(self) - len_other:]:
                        old_start = chunk.gallery_start or 1
                        chunk.gallery_start = old_start + gm.dest_size - gm.num_deleted
                        chunk.save()

        other.delete()


    @transaction.atomic
    def prepend_history(self, other):
        """Prepend history from all the other book's chunks to own."""
        assert self != other

        for i in range(len(self), len(other)):
            title = u"pusta część %d" % i
            chunk = self.add(slugify(title), title)
            chunk.commit('')

        for i in range(len(other)):
            self[i].prepend_history(other[0])

        assert not other.chunk_set.exists()
        other.delete()

    def split(self):
        """Splits all the chunks into separate books."""
        self.title
        for chunk in self:
            book = Book.objects.create(title=chunk.title, slug=chunk.slug,
                    public=self.public, gallery=self.gallery)
            book[0].delete()
            chunk.book = book
            chunk.number = 1
            chunk.save()
        assert not self.chunk_set.exists()
        self.delete()

    # State & cache
    # =============

    def last_published(self):
        try:
            return self.publish_log.all()[0].timestamp
        except IndexError:
            return None

    def assert_publishable(self):
        assert self.chunk_set.exists(), _('No chunks in the book.')
        try:
            changes = self.get_current_changes(publishable=True)
        except self.NoTextError:
            raise AssertionError(_('Not all chunks have publishable revisions.'))

        from librarian import NoDublinCore, ParseError, ValidationError

        try:
            bi = self.wldocument(changes=changes, strict=True).book_info
        except ParseError, e:
            raise AssertionError(_('Invalid XML') + ': ' + unicode(e))
        except NoDublinCore:
            raise AssertionError(_('No Dublin Core found.'))
        except ValidationError, e:
            raise AssertionError(_('Invalid Dublin Core') + ': ' + unicode(e))

        valid_about = self.correct_about()
        assert bi.about == valid_about, _("rdf:about is not") + " " + valid_about

    def publishable_error(self):
        try:
            return self.assert_publishable()
        except AssertionError, e:
            return e
        else:
            return None

    def hidden(self):
        return self.slug.startswith('.')

    def is_new_publishable(self):
        """Checks if book is ready for publishing.

        Returns True if there is a publishable version newer than the one
        already published.

        """
        new_publishable = False

apps/cover/models.py
# -*- coding: utf-8 -*-
#
# This file is part of FNP-Redakcja, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.contrib.sites.models import Site
from cover.utils import URLOpener


class OverwriteStorage(FileSystemStorage):

    def get_available_name(self, name, max_length=None):
        self.delete(name)
        return name


class Image(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    author = models.CharField(max_length=255, verbose_name=_('author'))
    license_name = models.CharField(max_length=255, verbose_name=_('license name'))
    license_url = models.URLField(max_length=255, blank=True, verbose_name=_('license URL'))
    source_url = models.URLField(verbose_name=_('source URL'), null=True, blank=True)
    download_url = models.URLField(unique=True, verbose_name=_('image download URL'), null=True, blank=True)
    file = models.ImageField(
        upload_to='cover/image', storage=OverwriteStorage(), editable=True, verbose_name=_('file'))

    class Meta:
        verbose_name = _('cover image')
        verbose_name_plural = _('cover images')

    def __unicode__(self):
        return u"%s - %s" % (self.author, self.title)

    @models.permalink
    def get_absolute_url(self):
        return 'cover_image', [self.id]

    def get_full_url(self):
        return "http://%s%s" % (Site.objects.get_current().domain, self.get_absolute_url())


@receiver(post_save, sender=Image)
def download_image(sender, instance, **kwargs):
    if instance.pk and not instance.file:
        t = URLOpener().open(instance.download_url).read()
        instance.file.save("%d.jpg" % instance.pk, ContentFile(t))

apps/cover/templates/cover/add_image.html
{% extends "catalogue/base.html" %}
{% load i18n %}

{% block add_js %}
    {{block.super}}
    <script>
        $(function() {
            var radio_buttons = $('input[type=radio][name=upload_type]'),
                image_fields = $('.upload_type input[type=text],input[type=file]');

            var enable_image_field = function(field) {
                field.attr('disabled', false);
            },
            disable_image_fields = function() {
                image_fields.attr('disabled', true);
            }

            radio_buttons.change(function() {
                var radio_button = $(this),
                    related_image_field = $('#'+radio_button.attr('data-for'));
                disable_image_fields();
                enable_image_field(related_image_field);
            });

            /* initial state */
            disable_image_fields();
            enable_image_field($('#id_download_url'));
        });
    </script>
{% endblock %}

{% block content %}
<h1>{% trans "Add image" %}</h1>


<form method="post">{% csrf_token %}
<input type="hidden" name='form_id' value="flickr" />
<table class='editable'><tbody>
    {{ ff.as_table }}
    <tr><td></td><td><button type="submit">{% trans "Load from Flickr" %}</button></td></tr>
</tbody></table>
</form>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form.non_field_errors }}
<table class='editable'><tbody>
    {% for field in form %}
        {% if field.name != 'download_url' and field.name != 'file' %}
        <tr>
            <th>{{field.errors}} {{field.label}}</th>
            <td>{{field}}</td>
        </tr>
        {% endif %}
    {% endfor %}
    <tr class="upload_type">
        <th>{{ form.download_url.errors }} <input style="width: auto;" checked data-for="id_download_url" type="radio" name="upload_type" value="url"/>{{form.download_url.label}}</th>
        <td>{{form.download_url}}</td>
        <th>{{ form.file.errors }} <input style="width: auto;" data-for="id_file" type="radio" name="upload_type" value="file"/> Lub {{form.file.label}}</th>
        <td>{{form.file}}</td>

    </tr>
    <tr><td></td><td><button type="submit">{% trans "Add image" %}</button></td></tr>
</tbody></table>
</form>


{% endblock %}

apps/cover/templates/cover/image_detail.html
{% extends "catalogue/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load build_absolute_uri from fnp_common %}

{% block content %}
<h1>{% trans "Cover image" %}</h1>

<div style="float: right; margin-bottom:1em;">

<a href="{{ object.file.url }}"><img
        src="{% thumbnail object.file "565x833" as thumb %}
                {{ thumb.url }}
             {% empty %}
                {{ object.file.url }}
             {% endthumbnail %}" />
    </a>
<br/><a href="{{ object.source_url }}">{{ object.title }}</a> by {{ object.author }},
    {% if object.license_url %}<a href="{{ object.license_url }}">{% endif %}
        {{ object.license_name }}
    {% if object.license_url %}</a>{% endif %}

<br/>{% trans "source" %}: {{ object.download_url }}
</div>


{% if editable %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{% endif %}
<table class='editable'><tbody>
    {{ form.as_table }}
    {% if editable %}
        <tr><td></td><td><button type="submit">{% trans "Change" %}</button></td></tr>
    {% endif %}
</tbody></table>
{% if editable %}</form>{% endif %}


<h2>{% trans "Used in:" %}</h2>
{% if object.book_set %}
<ul>
    {% for book in object.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>{% trans "None" %}</p>
{% endif %}


<textarea style="width:100%" rows="5">
&lt;dc:relation.coverImage.url xmlns:dc="http://purl.org/dc/elements/1.1/">{{ object.file.url|build_absolute_uri:request }}&lt;/dc:relation.coverImage.url>
&lt;dc:relation.coverImage.attribution xmlns:dc="http://purl.org/dc/elements/1.1/">{{ object.author }}, {{ object.license_name }}&lt;/dc:relation.coverImage.attribution>
&lt;dc:relation.coverImage.source xmlns:dc="http://purl.org/dc/elements/1.1/">{{ object.get_full_url }}&lt;/dc:relation.coverImage.source>
</textarea>
{% endblock %}

apps/cover/templates/cover/image_list.html
{% extends "catalogue/base.html" %}
{% load i18n %}
{% load thumbnail pagination_tags %}


{% block content %}
<h1>{% trans "Cover images" %}</h1>

{% if can_add %}
    <a href="{% url 'cover_add_image' %}">{% trans "Add new" %}</a>
{% endif %}

<ul>
{% autopaginate object_list 100 %}
{% for image in object_list %}
    <a href="{{ image.get_absolute_url }}" style="display:inline-block; width:200px;">
    
    <img style="height: 100px"
        src="{% thumbnail image.file "x100" as thumb %}
                {{ thumb.url }}
             {% empty %}
                {{ image.file.url }}
             {% endthumbnail %}" />
        <br/>
        {{ image }}</a>
{% endfor %}
{% paginate %}
</ul>

{% endblock %}